services:
  h2:
    image: oscarfonts/h2
    container_name: h2
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -ifNotExists"
    networks:
      - demo

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - h2
    environment:
      SPRING_PROFILES_ACTIVE: jpa
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/mem:demo_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - demo

networks:
  demo:
